# Generated by Django 2.1.1 on 2018-10-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
